name: ci

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Use Node.js 14.x
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
      with:
        node-version: 18
    - run: npm i
    # - run: npm run tests
    - run: npm run lint:ts