name: Deploy library on NPM

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

            - name: Push package to npmjs.com
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - run: yarn install
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}